name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./reddify-apigateway/reddify-apigateway.csproj

    - name: Build
      run: dotnet build ./reddify-apigateway/reddify-apigateway.csproj --no-restore

    - name: Test
      run: dotnet test ./reddify-apigateway/reddify-apigateway.csproj --no-build --verbosity normal

    - name: Build and push Docker image
      run: |
        docker build -t anwarict/apigatewayy .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push anwarict/apigatewayy:latest
